models/user.py
import uuid

from flask import session

from werkzeug.security import generate_password_hash, check_password_hash

from static.common.database import Database
from models.appointment import Appointment


class User(object):
    def __init__(self, username, email, full_name, phone_number, appointments=None, password=None, pw_hash=None, _id=None):
        self.username = username
        self.email = email
        self.full_name = full_name
        self.phone_number = phone_number
        self.pw_hash = pw_hash
        self.set_password(password)
        self.appointments = [] if appointments is None else appointments
        self._id = uuid.uuid4().hex if _id is None else _id

    def set_password(self, password):
        if self.pw_hash is None:
            self.pw_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.pw_hash, password)

    def login(self):
        session['username'] = self.username

    @staticmethod
    def logout():
        session['username'] = None

    def first_name(self):
        return self.full_name.split(' ')[0]

    def make_appointment(self, date, time):
        new_app = Appointment(self._id, date, time)
        self.appointments.append(new_app)
        new_app.save_to_db()

    def populate_appointments(self):
        populated = []
        for _id in self.appointments:
            populated.append(Appointment.find_by_id(_id))
        return populated

    def save_to_db(self):
        Database.insert('users', self.json())

    def update(self):
        Database.update_by_id('users', self._id, self.json())

    def json(self):
        return {
            'username': self.username,
            'email': self.email,
            'full_name': self.full_name,
            'phone_number': self.phone_number,
            'appointments': self.appointments,
            'pw_hash': self.pw_hash,
            '_id': self._id
        }

    @classmethod
    def find_by_id(cls, _id):
        user_data = Database.find_one('users', {'_id': _id})
        return cls(**user_data)

    @classmethod
    def find_by_email(cls, email):
        user_data = Database.find_one('users', {'email': email})
        return cls(**user_data)

    @classmethod
    def find_by_username(cls, username):
        user_data = Database.find_one('users', {'username': username})
        return cls(**user_data)

app.py
import os
from flask import Flask, render_template, request, session

from models.users.user import User
from static.common.database import Database

app = Flask(__name__)
secret = os.urandom(24)
app.secret_key = secret


@app.before_first_request
def initialize():
    Database.initialize()


from models.users.views import user_blueprint
app.register_blueprint(user_blueprint, url_prefix='/users')


@app.route('/')
def home():
        return render_template('home.html')





@app.route('/appointment', methods=['GET', 'POST'])
def appointment():
    if request.method == 'POST':
        user = User.find_by_username(session['username'])
        user.make_appointment(request.form['date'], request.form['time'])
        user.update()
        appointments = user.populate_appointments()

        return render_template('profile.html', user=user, appointments=appointments)

    else:
        return render_template('new_appointment.html')


if __name__ == '__main__':
    app.run(port=4990)

models/users/views.py
from flask import Blueprint, render_template, request, redirect, session

from models.users.user import User

user_blueprint = Blueprint('user_blueprint', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        user = User.find_by_username(username)
        if user is not None and user.check_password(password):
            user.login()
            return redirect('users/profile')
        else:
            return 'The username or password was incorrect.'
    else:
        return render_template('users/login.html')


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        user = User(request.form['username'],
                    request.form['email'],
                    request.form['full_name'],
                    request.form['phone_number'],
                    [],
                    request.form['password'])
        user.save_to_db()
        user.login()
        return redirect('users/profile')

    else:
        return render_template('users/register.html')


@user_blueprint.route('/profile', methods=['GET', 'POST'])
def profile():
    user = User.find_by_username(session['username'])
    appointments = user.populate_appointments()

    return render_template('users/profile.html', appointments=appointments)

templates/appointment.html
{% extends 'base.html' %}

{% block content %}

<form action='/appointment' method="post">
    <div class="form-group">
        <h1>Book en tid:</h1>
    </div>
    <div class="form-group">
        <label for="date">Vælg en Dato:</label>
        <input type="date" name="date" id="date">  
    </div>
    <div class="'form-group">
        <label for="time">Vælg et Tidspunkt:</label>
        <input type="time" name="time" id="time" step="1800">
    </div>
    <div class="form-group bnt bnt-primary">
        <input type="submit">
    </div>
    
</form>

{% endblock %}

templates/appointment/new_appointment.html
{% extends 'base.html' %}

{% block content %}

<form action='/appointment' method="post">
    <div class="form-group">
        <h1>Book en tid:</h1>
    </div>
    <div class="form-group">
        <label for="date">Vælg en Dato:</label>
        <input type="date" name="date" id="date">
    </div>
    <div class="'form-group">
        <label for="time">Vælg et Tidspunkt:</label>
        <input type="time" name="time" id="time" step="1800">
    </div>
    <div class="form-group bnt bnt-primary">
        <input type="submit">
    </div>
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Odensefotografen</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/main.css')}}"/>
</head>
<body>

<div class="page-wrap">


        {% include 'navbar.html' %}

        <section id="main">

        {% block content %}

        {% endblock %}

        {% include 'contact.html' %}

    </section>
</div>
<!-- Scripts -->
    <script src="{{ url_for('static', filename='assets/js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/jquery.poptrox.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/jquery.scrolly.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/skel.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/util.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
</body>
</html>

templates/contact.html
<!-- Contact -->
<section id="contact">
    <!-- Social -->
    <div class="social column">
        <h3>Om Mig</h3>
        <p>Mus sed interdum nunc dictum rutrum scelerisque erat a parturient condimentum potenti dapibus vestibulum
            condimentum per tristique porta. Torquent a ut consectetur a vel ullamcorper a commodo a mattis ipsum class
            quam sed eros vestibulum quisque a eu nulla scelerisque a elementum vestibulum.</p>
        <p>Aliquet dolor ultricies sem rhoncus dolor ullamcorper pharetra dis condimentum ullamcorper rutrum vehicula id
            nisi vel aptent orci litora hendrerit penatibus erat ad sit. In a semper velit eleifend a viverra adipiscing
            a phasellus urna praesent parturient integer ultrices montes parturient suscipit posuere quis aenean.
            Parturient euismod ultricies commodo arcu elementum suspendisse id dictumst at ut vestibulum conubia quisque
            a himenaeos dictum proin dis purus integer mollis parturient eros scelerisque dis libero parturient
            magnis.</p>
        <h3>Følg Mig</h3>
        <ul class="icons">
            <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
            <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
        </ul>
    </div>

    <!-- Form -->
    <div class="column">
        <h3>Skriv til Mig</h3>
        <form action="#" method="post">
            <div class="field half first">
                <label for="name">Navn</label>
                <input name="name" id="name" type="text" placeholder="Navn">
            </div>
            <div class="field half">
                <label for="email">Email</label>
                <input name="email" id="email" type="email" placeholder="Email">
            </div>
            <div class="field">
                <label for="message">Besked</label>
                <textarea name="message" id="message" rows="6" placeholder="Besked"></textarea>
            </div>
            <ul class="actions">
                <li><input value="Send Besked" class="button" type="submit"></li>
            </ul>
        </form>
    </div>

</section>

<!-- Footer -->
<footer id="footer">
    <div class="copyright">
        &copy; OdenseFotografen - Danmarksgade 59 - 5000 Odense C - Tlf. 28195498 -
    </div>
</footer>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<!-- Banner -->
<section id="banner">
    <div class="inner">
        <h1>OdenseFOTOGRAFEN</h1>
        <p>Fotografi til betalelige priser, på dinne premisser. </p>
        <ul class="actions">
            <li><a href="#galleries" class="button alt scrolly big">Continue</a></li>
        </ul>
    </div>
</section>

<!-- Gallery -->
<section id="galleries">

    <!-- Photo Galleries -->
    <div class="gallery">
        <header class="special">
            <h2>Mine Billeder</h2>
        </header>
        <div class="content">
            <div class="media">
                <a href="static/images/fulls/01.jpg"><img src="static/images/thumbs/01.jpg" alt=""
                                                   title="This right here is a caption."/></a>
            </div>
            <div class="media">
                <a href="static/images/fulls/05.jpg"><img src="static/images/thumbs/05.jpg" alt=""
                                                   title="This right here is a caption."/></a>
            </div>
            <div class="media">
                <a href="static/images/fulls/09.jpg"><img src="static/images/thumbs/09.jpg" alt=""
                                                   title="This right here is a caption."/></a>
            </div>
            <div class="media">
                <a href="static/images/fulls/02.jpg"><img src="static/images/thumbs/02.jpg" alt=""
                                                   title="This right here is a caption."/></a>
            </div>
            <div class="media">
                <a href="static/images/fulls/06.jpg"><img src="static/images/thumbs/06.jpg" alt=""
                                                   title="This right here is a caption."/></a>
            </div>
            <div class="media">
                <a href="static/images/fulls/10.jpg"><img src="static/images/thumbs/10.jpg" alt=""
                                                   title="This right here is a caption."/></a>
            </div>
            <div class="media">
                <a href="static/images/fulls/03.jpg"><img src="static/images/thumbs/03.jpg" alt=""
                                                   title="This right here is a caption."/></a>
            </div>
            <div class="media">
                <a href="static/images/fulls/07.jpg"><img src="static/images/thumbs/07.jpg" alt=""
                                                   title="This right here is a caption."/></a>
            </div>
        </div>
        <footer>
            <a href="#" class="button big">Se Galleriet</a>
            <a href="#" class="button big button2">Se Priser</a>
        </footer>
    </div>
</section>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <div class="form-group col-md-6">
        <h1>Login</h1>
    </div>

    <form action="/login" method="post">
        <div class="form-group col-md-6">
            <label for="username">Username:</label>
            <input type='text' class="form-control" id="username" name="username" >
        </div>

        <div class="form-group col-md-6">
            <label for='password'>Password:</label>
            <input type='password' class="form-control" id='password' name='password'>
        </div>

        <div class="form-group col-md-6">
            <input type='submit' class="btn btn-primary">
        </div>
    </form>

{% endblock %}

templates/navbar.html
<!-- Nav -->
<nav id="nav">
    <ul>
        <li><a href="/" class="active"><span class="icon fa-home"></span></a></li>
        <li><a href="#"><span class="icon fa-camera-retro"></span></a></li>
        <li><a href="#"><span class="icon fa-file-text-o"></span></a></li>
        <li><a href="users/login"><span class="icon fa-user"></span></a></li>
    </ul>
</nav>

templates/profile.html
{% extends  'base.html' %}

{% block content %}

    <h1>Velkommen {{ user.first_name() }}!</h1>

    <div>
        <h4>Aftaler:</h4>
        {% if appointments is undefined %}
        <p>Du har ikke nogle nuværende aftaler med OdenseFotografen</p>
        <a href="{{url_for('appointment')}}"><button type="button" class="btn btn-success">Book Aftale</button></a>
        {% else %}
        <ul>
            {% for item in appointments %}
                <li>
                    {{ item.as_text() }}
                </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<!-- Header -->
<header id="header">
    <div>Odense<span>FOTOGRAFEN</span></div>
</header>

<!-- Section -->
<section>
    <div class="inner">
        <header>
            <h1>Login</h1>
        </header>
        <div class="login-form">
            <form action="{{ url_for('user_blueprint.login') }}" method="post">
                <div class="field">
                    <label for="username">Username:</label>
                    <input type='text' id="username" name="username">
                </div>

                <div class="field">
                    <label for='password'>Password:</label>
                    <input type='password' id='password' name='password'>
                </div>

                <div class="actions">
                    <input value="Login" class="button" type="submit">
                    <a href="#" class="button register-button">Register</a>
                </div>
            </form>
        </div>
    </div>
</section>


{% endblock %}

templates/users/profile.html
{% extends  'base.html' %}

{% block content %}

    <h1>Velkommen til din profil!</h1>

    <div>
        <h4>Aftaler:</h4>
        {% if appointments is undefined %}
        <p>Du har ikke nogle nuværende aftaler med OdenseFotografen</p>
        <a href="#"><button type="button" class="btn btn-success">Book Aftale</button></a>
        {% else %}
        <ul>
            {% for item in appointments %}
                <li>
                    {{ item.as_text() }}
                </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block content %}

<h2>Register</h2>

<form action="{{ url_for('user_blueprint.register') }}" method="post" class="form-control">
    <div class="form-row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="username">Brugernavn:</label>
                <input type="text" id="username" name="username" placeholder="Brugernavn" class="form-control">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" placeholder="Password" class="form-control">
            </div>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" name="email" id="email" placeholder="Email@yourdomain.com" class="form-control">
            </div>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="full_name">Fuldt Navn:</label>
                <input type="text" id="full_name" name="full_name" placeholder="Fuldt Navn" class="form-control">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="phone_number">Telefon Nummer:</label>
                <input type="text" id="phone_number" name="phone_number" placeholder="Telefon Nummer"
                       class="form-control">
            </div>
        </div>
    </div>

    <div class="form-group">
        <input type='submit' class="btn btn-default">
    </div>
</form>
{% endblock %}